using OopFactory.X12.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OopFactory.X12.Parsing.Model.Typed.Enums
{
    public enum PlaceOfServiceCodes
    {
        [EDIFieldValue("1")]
        Pharmacy,
        [EDIFieldValue("3")]
        School,
        [EDIFieldValue("4")]
        HomelessShelter,
        [EDIFieldValue("5")]
        IndianHealthServiceFreeStandingFacility,
        [EDIFieldValue("6")]
        IndianHealthServiceProviderBasedFacility,
        [EDIFieldValue("7")]
        Tribal638FreeStandingFacility,
        [EDIFieldValue("8")]
        Tribal638ProviderBasedFacility,
        [EDIFieldValue("9")]
        PrisonCorrectionalFacility,
        [EDIFieldValue("11")]
        Office,
        [EDIFieldValue("12")]
        Home,
        [EDIFieldValue("13")]
        AssistedLivingFacility,
        [EDIFieldValue("14")]
        GroupHome,
        [EDIFieldValue("15")]
        MobileUnit,
        [EDIFieldValue("16")]
        TemporaryLodging,
        [EDIFieldValue("17")]
        WalkInRetailHealthClinic,
        [EDIFieldValue("18")]
        PlaceofEmploymentWorksite,
        [EDIFieldValue("20")]
        UrgentCareFacility,
        [EDIFieldValue("21")]
        InpatientHospital,
        [EDIFieldValue("22")]
        OutpatientHospital,
        [EDIFieldValue("23")]
        EmergencyRoomHospital,
        [EDIFieldValue("24")]
        AmbulatorySurgicalCenter,
        [EDIFieldValue("25")]
        BirthingCenter,
        [EDIFieldValue("26")]
        MilitaryTreatmentFacility,
        [EDIFieldValue("31")]
        SkilledNursingFacility,
        [EDIFieldValue("32")]
        NursingFacility,
        [EDIFieldValue("33")]
        CustodialCareFacility,
        [EDIFieldValue("34")]
        Hospice,
        [EDIFieldValue("41")]
        AmbulanceLand,
        [EDIFieldValue("42")]
        AmbulanceAirorWater,
        [EDIFieldValue("49")]
        IndependentClinic,
        [EDIFieldValue("50")]
        FederallyQualifiedHealthCenter,
        [EDIFieldValue("51")]
        InpatientPsychiatricFacility,
        [EDIFieldValue("52")]
        PsychiatricFacilityPartialHospitalization,
        [EDIFieldValue("53")]
        CommunityMentalHealthCenter,
        [EDIFieldValue("54")]
        IntermediateCareFacilityMentallyRetarded,
        [EDIFieldValue("55")]
        ResidentialSubstanceAbuseTreatmentFacility,
        [EDIFieldValue("56")]
        PsychiatricResidentialTreatmentCenter,
        [EDIFieldValue("57")]
        NonResidentialSubstanceAbuseTreatmentFacility,
        [EDIFieldValue("60")]
        MassImmunizationCenter,
        [EDIFieldValue("61")]
        ComprehensiveInpatientRehabilitationFacility,
        [EDIFieldValue("62")]
        ComprehensiveOutpatientRehabilitationFacility,
        [EDIFieldValue("65")]
        EndStageRenalDiseaseTreatmentFacility,
        [EDIFieldValue("71")]
        PublicHealthClinic,
        [EDIFieldValue("72")]
        RuralHealthClinic,
        [EDIFieldValue("81")]
        IndependentLaboratory,
        [EDIFieldValue("99")]
        OtherPlaceofService,
    }
}
