//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OopFactory.X12.Parsing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OopFactory.X12.Parsing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heierchical Loop {0} cannot be added to transaction set {1} because it&apos;s specification cannot be identified..
        /// </summary>
        internal static string X12ParserInvalidHLoopSpecification {
            get {
                return ResourceManager.GetString("X12ParserInvalidHLoopSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment {0} does not have a matching {1} segment preceding it..
        /// </summary>
        internal static string X12ParserMismatchSegment {
            get {
                return ResourceManager.GetString("X12ParserMismatchSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment &apos;{0}&apos; cannot occur before a {1} segment..
        /// </summary>
        internal static string X12ParserMissingPrecedingSegment {
            get {
                return ResourceManager.GetString("X12ParserMissingPrecedingSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file contains more than one interchange, you must use ParseMultiple instead of Parse to get all the records in this file..
        /// </summary>
        internal static string X12ParserParseError {
            get {
                return ResourceManager.GetString("X12ParserParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA segment and terminator is expected to be at least 106 characters..
        /// </summary>
        internal static string X12ReaderInvalidHeader {
            get {
                return ResourceManager.GetString("X12ReaderInvalidHeader", resourceCulture);
            }
        }
    }
}
